name: CI Pipeline

on:
  push:
    branches:
      - master  # Spécifie la branche où un push déclenchera le workflow

jobs:
  php-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP script
        run: php -l index.php # Nom du fichier index

  build:
    runs-on: self-hosted
    needs: php-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: docker login localhost:5000 -u username -p password  # Remplace avec tes infos de connexion

      - name: Pull Docker image from local registry
        run: docker pull localhost:5000/myapp:latest

      - name: Run Docker container
        run: docker run -d -p 8080:80 localhost:5000/myapp:latest

  push-dockerhub:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ":@Azertyqsd82" | docker login -u "eloiselbc" --password-stdin

      - name: Tag Docker image for Docker Hub
        run: docker tag myapp:latest eloiseLBC/myapp:latest  # Remplace "eloiseLBC" par ton identifiant Docker Hub

      - name: Push Docker image to Docker Hub
        run: docker push eloiseLBC/myapp:latest

