jobs:
  php-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP script
        run: php -l my-file.php

  build:
    runs-on: self-hosted
    needs: php-test  # Exécuter après le test PHP
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp:latest .
