name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  php-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP script
        run: php -l my-file.php  # Remplace 'my-file.php' par le nom de ton fichier PHP à vérifier

  build:
    runs-on: self-hosted
    needs: php-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: docker login localhost:5000 -u username -p password  # Remplace avec tes infos de connexion

      - name: Pull Docker image from local registry
        run: docker pull localhost:5000/myapp:latest

      - name: Run Docker container
        run: docker run -d -p 8080:80 localhost:5000/myapp:latest

  push-dockerhub:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image for Docker Hub
        run: docker tag myapp:latest mydockerhubuser/myapp:latest

      - name: Push Docker image to Docker Hub
        run: docker push mydockerhubuser/myapp:latest
